#!/usr/bin/env python3
"""Independent CPU audit of fresh V11 Resurface on validated V10 packed state.

Reconstructs fixture arithmetic, training schedules, checkpoint/export contents,
and PPL/MK statistics. Recorded GPU logits are not regenerated by this audit.
"""
from __future__ import annotations
import argparse
import copy
import json
import math
import os
from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
import audit_state_ppl_v10 as v10
import audit_state_ppl_v6 as v6
from audit_state_first_v5 import shapes,scaler_next,factor,check_optimizer_independent
from audit_quant_first import sha,need,finite,close,tokhash,read,recompute_pair,SOURCE,TOKENIZER,PROSE_FILE,PROSE_MANIFEST,VALIDATION_TOKENS
from audit_state_repair import hash_inventory,tensor_sha,frozen,cache_check,scores
from audit_state_repair import replay
from audit_resurface_more import audit_backend_policy

PROTOCOL='cebe06473806d74726ac006ff6d5dd316f4fdcfb779eb47f5af271ddb1fa04a6'
FORMAT='MAMBA2_STATE_RESURFACE_V11_AUDIT_V1'
V2_TRAINER='547e5b64904a273cd96a7d77624e5225a67edb9fa683950a43efc2d4171392a6'
NUMERIC_PROTOCOL='24466642ce87c75fc2136a42ed14e69733c462b507a0be82c062b4da7f836bcb'
TRAIN_MANIFEST='451b8703c21120667ef0ea272c21a10d4cd4561779a7b9663773ae47981600c0'
SELECTED='a77bbd86ae609d8ef7cf90f10d0904cf95b4df8e059c9ea6cb2fd12886436fb8'
RECEIPT='4dbc05cef7f3cd3b5bb43e65c0f25a1befdee2218aef3a476291a43093645b4c'
TABLE='b1865e81ff3fbed028027a883872aef9bb91e614e7cf08c72211496a78aeb597'
V10_SELECTED='598b7d3f8088d58513c4ab99aaf911543b0c355e02d9e79cb59a734c55a3f610'
V10_COMPARISON='d0a86c047d992377f8a6cf9c996d8b5525f03309497d378b814dd22d39ddea57'
V10_AUDIT='31d93219972466f6c62b8e1036c4de6cceee1d4c53d438faffeb02853c0affe5'
V10_AUDITOR='4f9e7bff5f237d86f3348f8bf05f173596b0d28fd1b41c3914eb33aaeb1f34f5'
S16='52f82f83258a2fa3160ea14585f1bd69e1d68d60d8f179d1f0987c636f6546ba'
LAYOUT='32_32_64'
BASELINE_PPL=8.186186562837207
CACHE=28499968
ADAPTER_BYTES=2308208
INITIAL_ADAPTER='fresh V=0,g=1,w=0,b=-4; no pretrained adapter or checkpoint'
INITIAL_SCALER=dict(scale=1024.,growth_factor=2.,backoff_factor=.5,growth_interval=2000,_growth_tracker=0)


def training_paths():
    return v10.run_paths()|{'scripts/'+name for name in ('train_state_resurface_v11.py',
        'state_ppl_training_scan_v11.py','state_ppl_training_v11.py','check_state_ppl_training_v11.py',
        'train_quant_first.py','train_resurface_more.py','evaluate_resurface_more.py')}|{
        'docs/'+name for name in ('STATE_RESURFACE_V11_PROTOCOL.md','QUANT_FIRST_PROTOCOL.md','RESURFACE_MORE_BACKEND_REPLAY.md')}


def audit_parent(args,torch):
    need(sha(ROOT/'docs/STATE_RESURFACE_V11_PROTOCOL.md')==PROTOCOL,'Frozen V11 protocol changed')
    for path,digest in ((args.calibration,SELECTED),(args.calibration.with_suffix('.json'),RECEIPT),
            (args.v10_full_dir/'full_selected.json',V10_SELECTED),
            (args.v10_full_dir/'full_comparison.json',V10_COMPARISON),(args.v10_full_audit,V10_AUDIT),
            (ROOT/'scripts/audit_state_ppl_v10.py',V10_AUDITOR)):
        need(sha(path)==digest,'Frozen V10 parent differs: '+str(path))
    selected=torch.load(args.calibration,map_location='cpu',weights_only=True)
    receipt=read(args.calibration.with_suffix('.json'));comparison=read(args.v10_full_dir/'full_comparison.json')
    archive=read(args.v10_full_dir/'full_selected.json');audit=read(args.v10_full_audit)
    hash_inventory(comparison['code_hashes'],v10.run_paths(),'V10 predecessor')
    need(audit['complete'] is True and audit['passed'] is True and audit['stage']=='full'
         and audit['cuda_initialized'] is False and audit['source_sha256']==V10_AUDITOR
         and comparison['target_pass'] is True and archive['ppl']['ppl']==BASELINE_PPL,
         'V10 audited achieved target required')
    need(set(comparison['report_sha256'])=={'v9_baseline','selected','restored_baseline'},'V10 arm inventory changed')
    for arm,digest in comparison['report_sha256'].items():
        need(sha(args.v10_full_dir/('full_'+arm+'.json'))==digest,'Archived V10 raw arm changed')
    for row in (selected,receipt):
        need(row['format']=='MAMBA2_STATE_PPL_V10_CALIBRATION_V1' and row['protocol_sha256']==v10.PROTOCOL
             and row['selected_layout']==row['selected_id']==LAYOUT and row['table_sha256']==TABLE
             and row['scale_mode']=='stored_scale' and row['int4_clip']==1.
             and row['adapter_used'] is False and row['heldout_used'] is False and row['mk_used'] is False,
             'V10 selected input provenance changed')
    table=selected['permutations']
    need(table.dtype==torch.uint8 and tuple(table.shape)==(56,8,128)
         and tensor_sha(table)==TABLE and torch.equal(table.sort(-1).values,torch.arange(128,dtype=torch.uint8).expand_as(table)),
         'V10 actual static table bytes differ')
    need(receipt['complete'] is True and receipt['sha256']==SELECTED and receipt['bytes']==args.calibration.stat().st_size,
         'V10 selected file receipt differs')
    for key in ('storage_descriptor_probe','storage_descriptor'):v10.audit_storage(archive[key],LAYOUT)
    need(archive['adapter_loaded'] is False and archive['adapter_sha256'] is None and archive['cache']['total_bytes']==CACHE,'V10 archive adapter/cache differs')
    nll=sum(row['nll'] for row in archive['ppl']['windows']);count=sum(row['target_tokens'] for row in archive['ppl']['windows'])
    need(len(archive['ppl']['windows'])==130 and count==264764 and archive['ppl']['nll']==nll
         and archive['ppl']['target_tokens']==count and math.exp(nll/count)==BASELINE_PPL,'V10 raw full arithmetic differs')
    binding=dict(calibration_sha256=SELECTED,calibration_receipt_sha256=RECEIPT,
        calibration_format='MAMBA2_STATE_PPL_V10_CALIBRATION_V1',layout=LAYOUT,table_sha256=TABLE,
        v10_full_selected_sha256=V10_SELECTED,v10_full_comparison_sha256=V10_COMPARISON,
        v10_full_audit_sha256=V10_AUDIT,selection_report_sha256=selected['selection_report_sha256'])
    return selected,archive,binding,dict(complete=True,selected_sha256=SELECTED,table_sha256=TABLE,
        comparison_sha256=V10_COMPARISON,audit_sha256=V10_AUDIT,raw_selected_sha256=V10_SELECTED,
        ppl=BASELINE_PPL,cache_bytes=CACHE,predecessor_scope='Hash-pinned independently audited V10 chain; raw parent arithmetic/table/storage rechecked')


def audit_data(args,tokenizer,torch,data,parent_binding):
    need(sha(ROOT/'scripts/train_quant_first.py')==V2_TRAINER and sha(ROOT/'docs/QUANT_FIRST_PROTOCOL.md')==NUMERIC_PROTOCOL,
         'Frozen training mathematics/protocol changed')
    manifest,_,examples=data.load_training(args.data_root,TRAIN_MANIFEST,tokenizer)
    need(manifest['protocol_sha256']==NUMERIC_PROTOCOL and len(examples)==1536,'Numeric TRAIN data differs')
    need(sha(args.prose_tokens)==PROSE_FILE and sha(args.prose_manifest)==PROSE_MANIFEST,'Prose TRAIN files differ')
    prose=read(args.prose_manifest);train=torch.load(args.prose_tokens,map_location='cpu',weights_only=True)
    need(prose['complete'] is True and prose['training_tokens_file_sha256']==PROSE_FILE
         and train.dtype==torch.int64 and tuple(train.shape)==(448,2048)
         and tokhash(train.flatten().tolist())==prose['training_tokens_sha256_int64le'], 'Prose token inventory/hash differs')
    audit=read(args.kernel_audit)
    need(audit.get('format')==FORMAT and audit.get('complete') is True and audit.get('passed') is True
         and audit.get('stage')=='checks' and audit.get('cuda_initialized') is False
         and audit.get('protocol_sha256')==PROTOCOL and audit.get('source_sha256')==sha(__file__)
         and audit.get('checks_sha256')==sha(args.kernel_checks),'Canonical independent kernel audit changed')
    binding={**parent_binding,'kernel_checks_sha256':sha(args.kernel_checks),'kernel_audit_sha256':sha(args.kernel_audit),
        'initial_adapter':INITIAL_ADAPTER,'fresh_initialization':True,'prior_adapter_loaded':False,
        'checkpoint_loaded':False,'v2_trainer_sha256':V2_TRAINER,
        'state_mode':'v10_32_32_64; exact packed stored-scale forward; 64-live STE backward',
        'teacher':'separate unadapted source, S16 per-token carry','source_checkpoint_sha256':SOURCE,
        'tokenizer_sha256':TOKENIZER,'protocol_sha256':PROTOCOL,'numeric_protocol_sha256':NUMERIC_PROTOCOL,
        'train_manifest_sha256':TRAIN_MANIFEST,'prose_manifest_sha256':PROSE_MANIFEST,
        'prose_tokens_sha256':PROSE_FILE,'prose_tokens_int64le_sha256':prose['training_tokens_sha256_int64le'],
        'adapter':'MAMBA2_POST_D_RESURFACE_FP16_V1','successful_updates':1536}
    return train,prose,binding


def probe_evidence(path,report,binding,train,torch,tensors,final_checkpoint):
    item=report['probe_evidence'];p=path.parent/item['file']
    need(Path(item['file']).name==item['file'] and sha(p)==item['sha256'] and p.stat().st_size==item['bytes'],
         'Raw parity evidence file differs')
    proof=torch.load(p,map_location='cpu',weights_only=True)
    need(proof['format']=='MAMBA2_STATE_RESURFACE_V11_TRAIN_PROOF_V1' and proof['binding']==binding,
         'Raw parity evidence binding differs')
    for phase,field in (('initialization','initialization_check'),('export','deployed_export_check')):
        entries=proof[phase];receipts=report[field]['probes']
        need(set(entries)=={'128','512'} and [r['probe_tokens'] for r in receipts]==[128,512], 'Both parity lengths required')
        for length,row in zip((128,512),receipts):
            entry=entries[str(length)];tokens=entry['token_ids'];a=entry['packed_hidden'];b=entry['training_hidden']
            need(tokens.dtype==torch.int64 and torch.equal(tokens,train[0,:length][None]),'Probe must use fixed TRAIN prefix')
            need(a.dtype==b.dtype==torch.float16 and tuple(a.shape)==tuple(b.shape)==(1,length,4096)
                 and bool(torch.isfinite(a).all()) and torch.equal(a,b),'Raw packed/training hidden tensors differ')
            need(row['probe_token_sha256']==tokhash(tokens.flatten().tolist())
                 and row['packed_hidden_sha256']==tensor_sha(a) and row['training_hidden_sha256']==tensor_sha(b)
                 and row['packed_training_forward_bitwise_equal'] is True and row['packed_probe_finite'] is True,
                 'Raw parity hash/receipt differs')
            cache_check(row['cache'],'old_sq',length)
        need(report[field]['cache']==receipts[0]['cache'],'Legacy128 cache alias differs')
    masters=proof['masters'];need(set(masters)==set(shapes()),'Raw final master inventory differs')
    for name,shape in shapes().items():
        value=masters[name]
        need(value.dtype==torch.float32 and tuple(value.shape)==shape and bool(torch.isfinite(value).all())
             and torch.equal(value.half(),tensors[name]),'Actual final FP32-to-FP16 export differs')
        if final_checkpoint is not None:
            need(torch.equal(value,final_checkpoint['masters'][name]),'Probe/master proof differs from final checkpoint')
    need(any(bool((v!=0).any()) for n,v in tensors.items() if n.endswith('.V_read')),
         'Nonzero trained export probe required')
    return dict(file_sha256=item['sha256'],lengths=[128,512],raw_initialization_and_export_exact=True,
        raw_master_casts_exact=True,nonzero_export=True)


def audit_training_report(path,mode,args,expected_binding,train,manifest,tokenizer,torch,data,smoke=None):
    report=read(path);limit=1 if mode=='smoke' else 1536
    need(report.get('format')=='MAMBA2_STATE_RESURFACE_V11_TRAIN_V1' and report.get('complete') is True
         and report.get('mode')==mode and report.get('successful_updates')==limit
         and report.get('planned_successful_updates')==1536 and limit<=report.get('attempts',-1)<=limit+8
         and 'error' not in report,'Incomplete fresh training/smoke report')
    need(sha(ROOT/'scripts/train_quant_first.py')==V2_TRAINER,'Reused v2 training math changed')
    hash_inventory(report['code_sha256'],training_paths(),'Fresh training')
    need(report['source_sha256']==sha(ROOT/'scripts/train_state_resurface_v11.py'),'Trainer source identity differs')
    need(report['binding']==expected_binding,'Fresh training selected table/data/recipe binding differs')
    fresh=report['fresh_initialization'];expected_shapes=shapes()
    need(fresh.get('all_224_masters_exact_fresh_values') is True and fresh.get('masters_dtype')=='float32'
         and fresh.get('master_tensors')==224 and fresh.get('parameters')==1154104
         and fresh.get('optimizer_state_empty') is True and fresh.get('optimizer_steps')==0
         and fresh.get('scaler_exact_initial') is True and fresh.get('scaler')==INITIAL_SCALER
         and fresh.get('prior_adapter_loaded') is False and fresh.get('checkpoint_loaded') is False,
         'Fresh master/optimizer/scaler initialization receipt differs')
    expected_initial={}
    for name,shape in expected_shapes.items():
        value={'V_read':0.,'g_read':1.,'router_w':0.,'router_b':-4.}[name.rsplit('.',1)[-1]]
        expected_initial[name]=tensor_sha(torch.full(shape,value,dtype=torch.float32))
    need(fresh['initial_tensor_sha256']==expected_initial,'Fresh constant master tensor hashes differ')
    names=[[f'layer{i}.{field}' for i in range(56) for field in fields]
           for fields in (('V_read','g_read'),('router_w','router_b'))]
    need(report['optimizer_parameter_names']==names,'Fresh optimizer parameter mapping differs')
    probe=tokhash(train[0,:128].tolist())
    init=report['initialization_check'];deployed=report['deployed_export_check']
    need(init.get('fresh_identity_matches_packed_bitwise') is True and init.get('probe_tokens')==128
         and init.get('probe_token_sha256')==probe and init.get('packed_probe_finite') is True,
         'Initial packed identity parity receipt differs')
    cache_check(init['cache'],'old_sq',128);cache_check(deployed['cache'],'old_sq',128)
    need(deployed.get('packed_training_forward_bitwise_equal') is True and deployed.get('probe_tokens')==128
         and deployed.get('probe_token_sha256')==probe and deployed.get('cache_unchanged_from_selected_unadapted') is True
         and deployed.get('packed_probe_finite') is True and init['cache']==deployed['cache'],
         'Actual exported FP16 packed parity evidence differs')
    frozen(report['frozen_base_check'])
    need(report.get('frozen_state_calibration_check') is True and report.get('selected_table_bytes_unchanged') is True
         and report.get('teacher_base_parameters_frozen') is True
         and report.get('export_master_check')==dict(all_master_casts_equal_export=True,master_tensors=224),
         'Frozen source/table/teacher or master-cast receipt differs')
    audit_backend_policy(report['backend_policy'],report['backend_final_check'])
    ordered=torch.randperm(1536,generator=torch.Generator().manual_seed(2026092803)).tolist()
    prose_order=torch.randperm(448,generator=torch.Generator().manual_seed(20260928)).tolist()
    need(prose_order==manifest['schedule'],'Prose schedule differs')
    need(report['schedule']==dict(seed=2026092803,successful_updates=1536,
        numeric_order_sha256_int64le=tokhash(ordered),prose_global_start=0,
        unchanged_v2_schedule_pair_optimizer_attempt=True),'Numeric schedule identity differs')
    cases=data.generate_cases('train');need(len(cases)==1536,'Numeric TRAIN inventory differs')
    success=overflows=0;scale=copy.deepcopy(INITIAL_SCALER);checkpoint_rows={}
    need(len(report['history'])==report['attempts'],'Attempt history missing')
    for attempt,row in enumerate(report['history'],1):
        need(success<limit and type(row['overflow']) is bool,'Unexpected training update/overflow flag')
        index=success;case=cases[ordered[index]]
        prompt=tokenizer.encode(case['prompt']);full=tokenizer.encode(case['prompt']+' '+case['answer'])
        need(full[:len(prompt)]==prompt,'Answer token prefix mismatch')
        need(row['attempt']==attempt and row['update_index']==index and row['schedule_entry']==ordered[index]
             and row['case_id']==case['id'] and row['prose_window']==prose_order[index%448]
             and row['prose_start']==512*((index//448)%4) and row['answer_targets']==len(full)-len(prompt),
             'Successful-update schedule/pairing differs')
        need(row['scaler_before']==scale and row['loss_scale_before']==scale['scale'],'Scaler before-attempt differs')
        scale=scaler_next(scale,row['overflow'])
        need(row['scaler_after']==scale and row['loss_scale']==scale['scale'],'Scaler transition differs')
        close(row['lr_factor'],factor(index),'Cosine schedule differs',tol=1e-14)
        need(len(row['learning_rates'])==2,'Learning-rate group count differs')
        for value,base_lr in zip(row['learning_rates'],(1e-4,3e-4)):
            close(value,base_lr*factor(index),'Learning-rate group value differs',tol=1e-14)
        need(all(finite(row[k]) for k in ('mk_ce','prose_ce','prose_kl','prose_closure','seconds'))
             and row['seconds']>=0 and row.get('successful_attempt_requires_v2_preclip_and_hidden_gradients_finite') is True
             and type(row['all_adapter_gradients_finite_after_attempt']) is bool,'Training loss/gradient evidence differs')
        if row['overflow']:
            overflows+=1;need(row['gradient_norm_before_clip'] is None,'Overflow unexpectedly updated parameters')
        else:
            success+=1
            need(row['all_adapter_gradients_finite_after_attempt'] is True
                 and finite(row['gradient_norm_before_clip']) and row['gradient_norm_before_clip']>=0,
                 'Successful update lacks finite gradients')
            if success%384==0:checkpoint_rows[success]=row
        need(row['successful_updates']==success,'Successful update count differs')
    need(success==limit and overflows<=8 and report['overflows']==overflows and report['attempts']==success+overflows
         and report['final_scaler']==scale,'Final step/total overflow/scaler differs')
    export=report['smoke_adapter'] if mode=='smoke' else report['adapter']
    need(Path(export['file']).name==export['file'],'Unsafe adapter filename')
    adapter_path=path.parent/export['file']
    need(sha(adapter_path)==export['sha256'] and adapter_path.stat().st_size==export['bytes']
         and export.get('roundtrip_bitwise_equal') is True and export.get('gate_mode')=='soft',
         'Serialized adapter identity differs')
    adapter=torch.load(adapter_path,map_location='cpu',weights_only=True)
    need(adapter['format']=='MAMBA2_POST_D_RESURFACE_FP16_V1' and adapter['gate_mode']=='soft'
         and adapter['variant']=='post-D native norm-prehook; memoryless cross-head mixing'
         and adapter['binding']==expected_binding
         and adapter['geometry']==[dict(width=4096,heads=128,head_dim=64)]*56,'Export adapter header differs')
    tensors=adapter['tensors'];need(set(tensors)==set(expected_shapes),'Adapter tensor inventory differs')
    for name,value in tensors.items():
        need(value.dtype==torch.float16 and tuple(value.shape)==expected_shapes[name] and bool(torch.isfinite(value).all())
             and tensor_sha(value)==export['tensor_sha256'][name],'Actual FP16 export tensor differs: '+name)
    need(sum(v.numel() for v in tensors.values())==export['parameters']==1154104
         and sum(v.numel()*v.element_size() for v in tensors.values())==export['payload_bytes']==2308208,
         'FP16 adapter parameter/byte accounting differs')
    nonzero=sum(int(torch.count_nonzero(v)) for n,v in tensors.items() if n.endswith('.V_read'))
    need(nonzero>0 and report['export_nonidentity_check']==dict(fp16_V_read_nonzero_elements=nonzero,fp16_V_read_nonzero=True),
         'Actual serialized FP16 mixing matrices must be nonzero')
    final_checkpoint=None
    if mode=='smoke':
        need(report['checkpoints']==[] and 'adapter' not in report and 'final_checkpoint' not in report
             and export.get('discarded') is True and export.get('candidate') is False
             and export['file']=='discarded_smoke_adapter_fp16.pt','Smoke was not explicitly discarded')
    else:
        need(smoke is not None and args.smoke_report.parent.resolve()!=path.parent.resolve(),
             'Formal training requires separate discarded smoke evidence')
        smoke_report,smoke_proof=smoke
        expected_smoke=dict(path=str(args.smoke_report),sha256=sha(args.smoke_report),discarded=True,
            successful_updates=1,formal_reinitializes_masters_optimizer_scaler=True,
            smoke_export_sha256=smoke_report['smoke_adapter']['sha256'],backend_policy_exact=True)
        # Stored path may be remote while auditing a copied evidence directory.
        actual_smoke=report['discarded_smoke_check'];need(Path(actual_smoke['path']).name==args.smoke_report.name,'Smoke path identity differs')
        need({k:v for k,v in actual_smoke.items() if k!='path'}=={k:v for k,v in expected_smoke.items() if k!='path'}
             and smoke_report['binding']==report['binding'] and smoke_report['code_sha256']==report['code_sha256']
             and smoke_report['backend_policy']==report['backend_policy'],'Formal/smoke identity or fresh restart binding differs')
        need(len(report['checkpoints'])==4,'Fixed recovery checkpoint count differs')
        final_checkpoint=None
        for step,item in zip((384,768,1152,1536),report['checkpoints']):
            checkpoint_path=path.parent/Path(item['path']).name
            need(checkpoint_path.name==item['file']==f'checkpoint_{step:04d}.pt'
                 and checkpoint_path.stat().st_size==item['bytes'] and sha(checkpoint_path)==item['sha256']
                 and item['successful_updates']==step and item['attempts']==checkpoint_rows[step]['attempt'],
                 'Recovery checkpoint receipt/count differs')
            checkpoint=torch.load(checkpoint_path,map_location='cpu',weights_only=True)
            need(checkpoint['format']=='MAMBA2_STATE_RESURFACE_V11_CHECKPOINT_V1' and checkpoint['binding']==expected_binding
                 and checkpoint['successful_updates']==step and checkpoint['attempts']==item['attempts']
                 and checkpoint['scaler']==checkpoint_rows[step]['scaler_after'],'Checkpoint binding/scaler differs')
            check_optimizer_independent(checkpoint,step,torch)
            final_checkpoint=checkpoint
        need(report['final_checkpoint']==report['checkpoints'][-1]
             and report['final_checkpoint_export_check']==dict(all_master_casts_equal_export=True,master_tensors=224,
                 optimizer_exact=True,scaler_exact=True,final_checkpoint_sha256=report['final_checkpoint']['sha256']),
             'Final checkpoint/export receipt differs')
        need(all(torch.equal(value.half(),tensors[name]) for name,value in final_checkpoint['masters'].items()),
             'Final checkpoint FP32 master casts do not equal actual exported FP16 tensors')
    raw=probe_evidence(path,report,expected_binding,train,torch,tensors,final_checkpoint)
    need(report['adapter_payload_bytes']==ADAPTER_BYTES,'Top-level adapter payload differs')
    proof=dict(complete=True,mode=mode,report_sha256=sha(path),adapter_sha256=export['sha256'],
        successful_updates=success,attempts=report['attempts'],overflows=overflows,
        independent_initial_master_hashes=True,independent_schedule_and_scaler=True,
        recovery_checkpoints_verified=0 if mode=='smoke' else 4,
        actual_final_checkpoint_cast_equals_export=mode=='formal',actual_serialized_FP16_parity_recorded=True,raw_probe_evidence=raw,
        optimizer_scope=('Smoke verifies actual final FP32 masters and casts, fresh empty optimizer and retry/scaler evidence; no stored final Adam moments.'
            if mode=='smoke' else 'Checks complete finite moments, mapping, recipe and step counts; does not recompute GPU gradients or Adam updates.'))
    return report,proof


def prediction_kind(row):
    prediction=row['prediction'];removed=row['condition']=='target_removed'
    if prediction==row['answer']:return 'removed_target_match' if removed else 'correct_target'
    if prediction is None:return 'unparseable'
    if any(int(prediction)==value for _,value in row['records']):
        return 'other_present_value' if removed else 'wrong_present_value'
    return 'not_present_value'


def group_summary(rows):
    categories={}
    for row in rows:
        key=prediction_kind(row);categories[key]=categories.get(key,0)+1
    n=len(rows);correct=sum(int(row['correct']) for row in rows)
    return dict(count=n,correct=correct,accuracy=correct/n if n else None,prediction_categories=dict(sorted(categories.items())))


def mk_summaries(rows):
    summary={condition:group_summary([r for r in rows if r['condition']==condition])
             for condition in ('normal','target_removed')}
    normal=[r for r in rows if r['condition']=='normal'];strata={}
    groupers={'normal_by_N':lambda r:str(r['N']), 'normal_by_template':lambda r:str(r['template']),
        'normal_by_N_template':lambda r:'N%d_t%d'%(r['N'],r['template']),
        'normal_by_N_query_position':lambda r:'N%d_p%d'%(r['N'],r['query_position']),
        'normal_by_N_position_quartile':lambda r:'N%d_q%d'%(r['N'],(r['query_position']*4)//r['N'])}
    for label,key in groupers.items():
        names=sorted(set(key(r) for r in normal))
        strata[label]={name:group_summary([r for r in normal if key(r)==name]) for name in names}
    return summary,strata


def audit_adapter_storage(row,adapted,export):
    expected=dict(loaded=adapted,tensors=224 if adapted else 0,parameters=1154104 if adapted else 0,
        fp16_payload_bytes=ADAPTER_BYTES if adapted else 0,resident_storage_bytes=ADAPTER_BYTES if adapted else 0,
        persistent_buffer_bytes=0,additional_recurrent_cache_bytes=0,ema_enabled=False,
        cache_plus_adapter_bytes=CACHE+(ADAPTER_BYTES if adapted else 0))
    if adapted:
        expected.update(serialized_file_bytes=export['bytes'],adapter_sha256=export['sha256'],
            tensor_sha256=export['tensor_sha256'],tensors_unchanged=True,
            scope='Actual distinct CUDA parameter storage; source weights, temporaries and allocator reserve excluded')
    need(row==expected,'Actual adapter residency/payload/buffers accounting differs')
    return expected


def primary_gates(ppl,baseline,mk_delta,lower,archive_exact,restored_exact,cache_equal,storage_equal,training_pass):
    return dict(ppl_no_worse_than_v10=finite(ppl) and ppl<=baseline,ppl_strictly_below_8p25=finite(ppl) and ppl<8.25,
        normal_mk_increases=mk_delta>0,paired95_lower_positive=lower>0,exact_archive_replay=archive_exact,
        exact_adapter_removal_replay=restored_exact,cache_same_budget=cache_equal,
        adapter_storage_verified=storage_equal,training_audit_passed=training_pass)


SPECIALS=('dyadic','rounded_scales','underflow','subnormal','wide_safe','zero')
GEOMETRIES=((2,19,4,19,2),(1,1,8,17,2),(1,65,4,19,2))
GRAD_FIELDS=('x','dt','B','C')
CHECK_PATHS={'scripts/'+name for name in ('state_ppl_training_scan_v11.py','state_ppl_training_v11.py',
    'check_state_ppl_training_v11.py','state_ppl_codec_v10.py','state_ppl_codec_v6.py')}|{
    'mamba2_recall/'+name for name in ('state_training.py','state_training_scan.py','state_codec.py','state_quant.py')}|{
    'docs/STATE_RESURFACE_V11_PROTOCOL.md'}


def expected_checks():
    names=['protocol_hash','cuda_uninitialized_before_tests']
    for special in SPECIALS:
        names.append('cpu_fixture_'+special)
        if special=='underflow':names.append('cpu_scale_underflow_defined_zero')
        if special=='subnormal':names.append('cpu_scale_subnormal_present')
    names += ['reject_chunk_'+v for v in ('0','257','True','1.5')]
    names += ['reject_trainable_'+v for v in ('A','D','dt_bias')]+['workspace_64_live_count']
    for name in tuple('random_'+str(i) for i in range(3))+tuple('controlled_'+s for s in SPECIALS):
        names += [name+'_full_token_partition',name+'_physical_52_byte_rows']
        if name.startswith('controlled_'):names.append(name+'_independent_packed_oracle')
        names += [name+'_carry_history_K'+str(k) for k in (1,8,13,32)]+[name+'_training_forward_exact']
        names += [name+'_ste_gradient_'+field for field in GRAD_FIELDS]
        names += [name+'_chunk_gradient_'+field for field in GRAD_FIELDS]
        names += [name+'_checkpoint_forward_exact',name+'_checkpoint_gradient',name+'_fresh_replay_exact']
    return names+['dead_future_gradients_exact_zero','dead_current_gradients_nonzero','production_geometry_finite']


def random_inputs(geometry,torch):
    batch,length,heads,dim,groups=geometry;gen=torch.Generator().manual_seed(2026092911)
    def sample(shape):return (torch.randn(shape,generator=gen)*.15).to(torch.float16)
    inputs=[sample((batch,length,heads,dim)),sample((batch,length,heads)),
        -torch.exp(torch.randn(heads,generator=gen)*.2),sample((batch,length,groups,128)),
        sample((batch,length,groups,128)),sample((heads,)),torch.full((heads,),-1.5,dtype=torch.float16)]
    table=torch.stack([torch.randperm(128,generator=gen) for _ in range(groups)]).to(torch.uint8)
    return inputs,table


def controlled_inputs(special,np,torch):
    length=65 if special=='dyadic' else 5
    order=np.stack([np.roll(np.arange(127,-1,-1),13*g) for g in range(2)]).astype(np.uint8)
    pattern8=np.array([-127,-126.5,-64,-1.5,-.5,0,.5,1.5,64,126.5,127],np.float32)
    pattern4=np.array([-7,-6.5,-4,-1.5,-.5,0,.5,1.5,4,6.5,7],np.float32)
    wanted=np.concatenate((np.resize(pattern8,32),np.resize(pattern4,32),(np.arange(64)%5-2).astype(np.float32)))
    if special=='rounded_scales':wanted[0]=127.0625;wanted[32]=7.00390625
    if special in ('underflow','subnormal','wide_safe'):
        wanted=np.sign(wanted)*np.float32({'underflow':2**-19,'subnormal':2**-11,'wide_safe':4096.}[special])
    if special=='zero':wanted.fill(0)
    x=np.empty((2,length,4,19),np.float16);B=np.empty((2,length,2,128),np.float16);C=np.zeros_like(B)
    for b in range(2):
        for h in range(4):
            exponents=(b+h+np.arange(19))%3-5
            x[b,:,h,:]=((-1.)**(b+h+np.arange(19))*2.**exponents)[None,:]
        for t in range(length):
            for g in range(2):
                B[b,t,g,order[g]]=(wanted*np.float32((1,1,-1,-1)[t%4])/np.float32(32)).astype(np.float16)
                C[b,t,g,order[g,(0,31,32,63,64,127)[t%6]]]=(-1.)**(b+g)*2**-8
    if special in ('underflow','subnormal'):x.fill(2**-5)
    arrays=[x,np.zeros((2,length,4),np.float16),np.zeros(4,np.float32),B,C,
        np.zeros(4,np.float16),np.full(4,32,np.float32)]
    return [torch.from_numpy(v) for v in arrays],torch.from_numpy(order)


def actual_carries(packed,shape,np,torch):
    batch,length,heads,dim=shape;result=[]
    expected=v10.independent_geometry(LAYOUT,batch,heads,dim,1)['tensors']
    need(len(packed)==length,'Every token actual packed state required')
    for entry in packed:
        need(set(entry)==set(expected),'Packed tensor inventory differs')
        buffers={}
        for name,spec in expected.items():
            value=entry[name]
            need(tuple(value.shape)==tuple(spec['shape']) and str(value.dtype)==spec['dtype']
                 and value.device.type=='cpu' and value.untyped_storage().nbytes()==spec['bytes'],
                 'Packed fixture has hidden padding/dtype/shape change')
            need(not value.is_floating_point() or bool(torch.isfinite(value).all()),'Packed scale nonfinite')
            buffers[name]=value.numpy()
        decoded=v10.decode_np(buffers,LAYOUT,np)
        need(np.isfinite(decoded).all() and not np.count_nonzero(decoded[...,64:]),'Decoded live/dead carry differs')
        result.append(torch.from_numpy(decoded))
    return torch.stack(result)


def controlled_recompute(inputs,table,packed,output,np,torch):
    x,raw,A,B,C,D,bias=[v.numpy().astype(np.float32) for v in inputs]
    order=table.numpy().astype(np.int64);batch,length,heads,dim=x.shape
    previous=np.zeros((batch,heads,dim,128),np.float32);results=[]
    for t in range(length):
        # All six fixed controlled fixtures have dt32/decay1 exactly.
        need(not raw[:,t].any() and not A.any() and np.all(bias==32),'Controlled scalar fixture changed')
        group=np.arange(heads)//(heads//len(order));perm=order[group]
        b=np.take_along_axis(B[:,t,group,:],perm[None],-1)
        c=np.take_along_axis(C[:,t,group,:],perm[None],-1)
        updated=(previous.astype(np.float64)+(b*np.float32(32))[:,:,None,:].astype(np.float32)*x[:,t,...,None]).astype(np.float32)
        product=updated*c[:,:,None,:]
        y=product[...,:32].sum(-1,dtype=np.float32)+product[...,32:64].sum(-1,dtype=np.float32)
        y+=product[...,64:].sum(-1,dtype=np.float32)+x[:,t]*D[None,:,None]
        results.append(y.astype(np.float16))
        expected=v10.quantize_np(updated,LAYOUT,np)
        need(all(np.array_equal(packed[t][k].numpy().view(np.uint8),v.view(np.uint8)) for k,v in expected.items()),
             'Independent controlled integer/scale/packing recurrence differs')
        previous=v10.decode_np(expected,LAYOUT,np)
    wanted=torch.from_numpy(np.stack(results,1))
    need(output.dtype==torch.float16 and torch.equal(wanted,output),'Independent controlled readout differs')


def independent_ste(inputs,table,carries,gy,torch):
    """Rebuild a separate CPU autograd graph from raw input and decoded bytes.

    It uses exact recorded numerical carries with a retained identity tangent;
    neither the GPU backward nor the checker's serialized reference is called.
    """
    leaves=[v.float().detach().requires_grad_(i in (0,1,3,4)) for i,v in enumerate(inputs)]
    x,raw,A,B,C,D,bias=leaves;batch,length,heads,dim=x.shape
    group=torch.arange(heads)//(heads//table.shape[0]);indices=table.long()[group]
    prev=torch.zeros((batch,heads,dim,128),dtype=torch.float32);outputs=[]
    for t in range(length):
        delta_input=raw[:,t]+bias
        # Recreate the declared elementary softplus expression without
        # importing the checker oracle, backward kernel or quantizer.
        delta=torch.where(delta_input<=20,torch.log(torch.exp(delta_input)+1),delta_input)
        decay=torch.exp(delta*A)
        bv=torch.gather(torch.index_select(B[:,t],1,group),2,indices[None].expand(batch,-1,-1))
        cv=torch.gather(torch.index_select(C[:,t],1,group),2,indices[None].expand(batch,-1,-1))
        addition=(bv*delta[...,None])[:,:,None,:]*x[:,t,...,None]
        state=(prev.to(torch.float64)*decay[...,None,None].to(torch.float64)+addition.to(torch.float64)).float()
        product=state*cv[:,:,None,:]
        y=product[...,:32].sum(-1)+product[...,32:64].sum(-1)
        y=y+(product[...,64:].sum(-1).double()+x[:,t].double()*D.double()[None,:,None]).float()
        outputs.append(y.half())
        retained=state[...,:64]
        prev=torch.cat((carries[t][...,:64]+(retained-retained.detach()),torch.zeros_like(state[...,64:])),dim=-1)
    out=torch.stack(outputs,1)
    return torch.autograd.grad(out,[leaves[i] for i in (0,1,3,4)],gy)


def gradient_facts(actual,expected,atol,rtol,torch):
    need(actual.dtype==torch.float16 and actual.shape==expected.shape and bool(torch.isfinite(actual).all())
         and bool(torch.isfinite(expected).all()),'Gradient dtype/shape/finiteness differs')
    a=actual.float();b=expected.half().float();error=(a-b).abs();bound=atol+rtol*b.abs()
    need(bool((error<=bound).all()),'Declared elementwise STE/replay gradient bound exceeded')
    return dict(max_absolute_error=float(error.max()),max_bound_ratio=float((error/bound).max()),
        relative_rms_error=float(error.square().mean().sqrt()/b.square().mean().sqrt().clamp_min(1e-12)),atol=atol,rtol=rtol)


def audit_checks(path,torch,np):
    report=read(path)
    need(report.get('format')=='MAMBA2_STATE_PPL_V11_TRAINING_CHECK_V1' and report.get('complete') is True
         and report.get('passed') is True and report.get('mode')=='gpu' and report.get('cuda_initialized') is True
         and report.get('protocol_sha256')==PROTOCOL and report.get('layout')==LAYOUT and 'error' not in report,
         'Completed actual GPU V11 checker required')
    hash_inventory(report['code_sha256'],CHECK_PATHS,'V11 numerical checker')
    need(report['criteria']==dict(forward='bitwise_equal',carry='every_token_bitwise_equal',
        cpu_controlled='raw_packed_bytes_and_readout_exact',ste_gradient=dict(atol=2e-5,rtol=.015),
        gradient_replay=dict(atol=2e-6,rtol=.002),live_coordinates=64,current_readout_coordinates=128),
        'Prospective numerical criteria changed')
    names=expected_checks();rows=report['checks']
    need([r['name'] for r in rows]==names and all(r['pass'] is True for r in rows),'Exact numerical check inventory differs')
    receipts={r['name']:r for r in rows};item=report['evidence'];p=Path(item['file'])
    if not p.is_file():p=path.parent/p.name
    need(sha(p)==item['sha256'] and p.stat().st_size==item['bytes'] and item['cases']==9,'Raw numerical evidence file changed')
    evidence=torch.load(p,map_location='cpu',weights_only=True)
    need(evidence['format']=='MAMBA2_STATE_PPL_V11_TRAINING_EVIDENCE_V1' and evidence['protocol_sha256']==PROTOCOL,
         'Raw numerical evidence header differs')
    case_names=tuple('random_'+str(i) for i in range(3))+tuple('controlled_'+s for s in SPECIALS)
    need(tuple(c['name'] for c in evidence['cases'])==case_names,'Fixed nine-fixture inventory differs')
    audited=[]
    for index,case in enumerate(evidence['cases']):
        name=case['name'];expected_inputs,table=(random_inputs(GEOMETRIES[index],torch) if index<3
            else controlled_inputs(SPECIALS[index-3],np,torch))
        inputs=case['inputs']
        need(len(inputs)==7 and all(a.dtype==b.dtype and torch.equal(a,b) for a,b in zip(inputs,expected_inputs))
             and case['table'].dtype==torch.uint8 and torch.equal(case['table'],table),'Raw fixture values/RNG/table changed: '+name)
        shape=tuple(inputs[0].shape);batch,length,heads,dim=shape
        output=case['deployed_output'];need(output.dtype==torch.float16 and tuple(output.shape)==shape
             and bool(torch.isfinite(output).all()),'Actual output geometry/finite scope differs')
        carries=actual_carries(case['packed'],shape,np,torch)
        need(receipts[name+'_physical_52_byte_rows']['actual_bytes']==batch*heads*dim*52,'Actual fixture packed byte count differs')
        if index>=3:controlled_recompute(inputs,table,case['packed'],output,np,torch)
        previous=torch.cat((torch.zeros_like(carries[:1]),carries[:-1]),0).permute(1,0,2,3,4)[...,:64]
        need([r['chunk_size'] for r in case['histories']]==[1,8,13,32],'History checkpoint inventory differs')
        for entry in case['histories']:
            need(entry['history'].dtype==entry['checkpoints'].dtype==torch.float32
                 and torch.equal(entry['history'],previous)
                 and torch.equal(entry['checkpoints'],previous[:,::entry['chunk_size']]),
                 'Every-token/chunk-start decoded carry differs')
        generator=torch.Generator().manual_seed(2026092912)
        gy=(torch.randn(shape,generator=generator)*(.00001 if name=='controlled_wide_safe' else .03)).half()
        need(case['gy'].dtype==torch.float16 and torch.equal(case['gy'],gy),'Raw upstream gradient RNG differs')
        gradients=independent_ste(inputs,table,carries,gy,torch)
        need(all(len(case[key])==4 for key in ('gradients','reference_gradients','alternate_chunk_gradients','checkpoint_gradients')),
             'Gradient parameter inventory differs')
        worst=0.
        for j,field in enumerate(GRAD_FIELDS):
            ref=case['reference_gradients'][j];expected=gradients[j]
            need(ref.dtype==torch.float32 and torch.equal(ref,expected),'Serialized reference differs from independently rebuilt CPU STE graph')
            values=gradient_facts(case['gradients'][j],expected,2e-5,.015,torch)
            need(all(receipts[name+'_ste_gradient_'+field][k]==v for k,v in values.items()),'STE error summary differs')
            worst=max(worst,values['max_bound_ratio'])
            values=gradient_facts(case['alternate_chunk_gradients'][j],case['gradients'][j],2e-6,.002,torch)
            need(all(receipts[name+'_chunk_gradient_'+field][k]==v for k,v in values.items()),'Chunk replay gradient summary differs')
            gradient_facts(case['checkpoint_gradients'][j],case['gradients'][j],2e-6,.002,torch)
        audited.append(dict(name=name,tokens=length,exact_packed_cpu_oracle=index>=3,
            every_token_carry_and_checkpoints_exact=True,independent_cpu_STE_gradients=True,worst_gradient_bound_ratio=worst))
    dead=evidence['dead_current_future'];inputs,table=random_inputs((2,5,4,19,2),torch)
    table=torch.arange(128,dtype=torch.uint8).repeat(2,1);inputs[3][...,:64]=0;inputs[4][...,:64]=0;inputs[5].zero_()
    need(torch.equal(dead['table'],table) and len(dead['inputs'])==7 and all(
        a.dtype==b.dtype and torch.equal(a,b) for a,b in zip(dead['inputs'],inputs)),'Dead/current fixture input differs')
    need(len(dead['gradients'])==4 and all(v.dtype==torch.float16 and bool(torch.isfinite(v).all())
         and torch.count_nonzero(v[:,:-1])==0 and torch.count_nonzero(v[:,-1])>0 for v in dead['gradients']),
         'Dead lanes block future gradients but must preserve current readout gradients')
    zero=torch.zeros((5,2,4,19,128),dtype=torch.float32);gy=torch.zeros_like(inputs[0]);gy[:,-1]=1
    expected=independent_ste(inputs,table,zero,gy,torch)
    for a,b in zip(dead['gradients'],expected):gradient_facts(a,b,2e-5,.015,torch)
    space=dict(carry_scratch_bytes=(64+32+1)*128*64*64*4,
        gradient_scratch_bytes=2048*(128*64+128+2*8*128)*4)
    space['total_scratch_bytes']=sum(space.values())
    need(all(receipts['workspace_64_live_count'][k]==v for k,v in space.items()),'Temporary training workspace arithmetic differs')
    need(receipts['production_geometry_finite']['geometry']==[1,64,128,64],'Production geometry finite receipt differs')
    return dict(complete=True,checks_sha256=sha(path),evidence_sha256=item['sha256'],checks=len(names),cases=audited,
        controlled_cases_recomputed=6,raw_dead_current_future_gradients_verified=True,training_workspace_2048=space,
        scope='Raw nine-fixture inputs, codes/scales, histories and gradients rederived on CPU; random forward delegation and production finite test remain hash-bound GPU receipts')


def audit_full(args,archive,parent_binding,training,training_proof,tokenizer,torch,np,data):
    from mamba2_recall.calibration import load_wikitext_tokens
    validation,dataset=load_wikitext_tokens(tokenizer,'validation')
    need(tokhash(validation.tolist())==VALIDATION_TOKENS,'Validation stream identity differs')
    windows=[(i,validation[i:min(i+2049,len(validation))].tolist()) for i in range(0,len(validation)-1,2048)]
    need(len(windows)==130 and sum(len(w)-1 for _,w in windows)==264764,'Full target population differs')
    cases=data.generate_cases('confirm');case_proof=data.validate_cases(cases,'confirm')
    need(len(cases)==768 and len([c for c in cases if c['condition']=='normal'])==384,'CONFIRM inventory differs')
    training_audit=read(args.training_audit)
    need(training_audit.get('format')==FORMAT and training_audit.get('stage')=='training'
         and training_audit.get('complete') is True and training_audit.get('passed') is True
         and training_audit.get('cuda_initialized') is False and training_audit.get('protocol_sha256')==PROTOCOL
         and training_audit.get('source_sha256')==sha(__file__)
         and training_audit.get('training_report_sha256')==sha(args.training_report)
         and training_audit.get('checks_sha256')==sha(args.kernel_checks)
         and training_audit.get('smoke_report_sha256')==sha(args.smoke_report)
         and training_audit.get('training')==training_proof,'Canonical training audit differs from current independent reconstruction')
    directory=args.eval_dir;comparison=read(directory/'full_comparison.json')
    arms=('v10_no_adapter','v10_resurface','restored_v10_no_adapter')
    need(comparison.get('format')=='MAMBA2_STATE_RESURFACE_V11_COMPARISON_V1'
         and comparison.get('complete') is True and comparison.get('stage')=='full'
         and comparison.get('protocol_sha256')==PROTOCOL and tuple(comparison['report_sha256'])==arms,
         'Fixed full comparison/arm inventory differs')
    expected_codes=training_paths()|{'scripts/run_state_resurface_v11.py','scripts/audit_state_resurface_v11.py'}
    hash_inventory(comparison['code_hashes'],expected_codes,'V11 full evaluation')
    common=dict(format='MAMBA2_STATE_RESURFACE_V11_EVAL_V1',stage='full',protocol_sha256=PROTOCOL,
        parent_binding=parent_binding,training_report_sha256=sha(args.training_report),
        training_audit_sha256=sha(args.training_audit),candidate_adapter_sha256=training['adapter']['sha256'],
        training_binding=training['binding'],dataset=dataset,
        confirm_case_sha256=data.sha_bytes(data.canonical_bytes(cases)),confirm_case_proof=case_proof,
        confirm_generation='Frozen resurface_data.generate_cases(confirm); full vocabulary greedy max12/EOS; first standalone six-digit integer',
        numeric_protocol_sha256=NUMERIC_PROTOCOL,candidate_table_sha256=TABLE,
        allocation_spec=v10.descriptor_independent(LAYOUT),heldout_used=True,heldout_used_for_selection=False,mk_used=True,
        s16_report_sha256=S16 if args.s16_report is not None else None,
        quality_scope='Historically exposed validation corpus and CONFIRM prompt families; no unseen-generalization claim')
    need(all(comparison.get(k)==common[k] for k in ('parent_binding','training_report_sha256','training_audit_sha256','candidate_adapter_sha256')),
         'Full comparison training/parent binding differs')
    outputs={};metrics={};digests={}
    for arm in arms:
        adapted=arm=='v10_resurface';path=directory/('full_'+arm+'.json');row=read(path);digests[arm]=sha(path)
        need(digests[arm]==comparison['report_sha256'][arm],'Full raw arm file changed')
        identity={**common,'arm':arm,'adapter_loaded':adapted,'adapter_sha256':training['adapter']['sha256'] if adapted else None}
        # The old independent PPL auditor deliberately excludes MK. Inspect the
        # unmodified PPL/cache/probe fields through a shallow copy without MK.
        ppl_only={k:v for k,v in row.items() if k!='mk'}
        v10.v8.audit_arm(ppl_only,windows,identity,v10.spec_for(LAYOUT),TABLE,comparison,False)
        need(row.get('allocation_storage_validated') is True and row.get('adapter_unchanged') is True
             and row.get('adapter_hooks_removed_after_arm') is True and row.get('mk_persistent_float_finite_checks_passed') is True
             and row.get('mk_runtime_table_unchanged') is True,'Full integrity/adapter removal receipt differs')
        for field in ('storage_descriptor_probe','storage_descriptor','storage_descriptor_mk'):
            v10.audit_storage(row[field],LAYOUT)
        need(row['storage_descriptor_probe']==row['storage_descriptor']==row['storage_descriptor_mk'],
             'Physical persistent allocation changed between PPL/MK')
        need(row['ppl_cache']==row['cache'],'PPL-end cache alias was overwritten during MK')
        v6.audit_cache(row['ppl_cache'],v10.spec_for(LAYOUT),len(windows[-1][1])-1)
        last=row['mk']['rows'][-1]
        v6.audit_cache(row['mk_cache'],v10.spec_for(LAYOUT),last['prompt_tokens']+len(last['generated_ids'])-1)
        # Decode/token checks from the unchanged CPU audit, followed by new
        # independently grouped classification/position accounting.
        basic={**row,'mk':{**row['mk'],'summary':{k:{a:b for a,b in v.items() if a!='prediction_categories'}
            for k,v in row['mk']['summary'].items()}}}
        metrics[arm]=scores(basic,windows,cases,tokenizer)
        summary,strata=mk_summaries(row['mk']['rows'])
        need(summary==row['mk']['summary'] and strata==row['mk']['strata']
             and all(r['prediction_category']==prediction_kind(r) for r in row['mk']['rows']),
             'Recall strata or wrong-present/unparseable/not-present classification differs')
        metrics[arm].update(summary=summary,strata=strata,
            adapter_storage=audit_adapter_storage(row['adapter_storage'],adapted,training['adapter']))
        outputs[arm]=row
    parent=outputs[arms[0]];candidate=outputs[arms[1]];restored=outputs[arms[2]]
    parent_expected=dict(complete=True,per_window_nll_exact=True,ppl_windows_repeated=130,target_tokens=264764,
        reset_hidden_exact=True,reset_cache_exact=True,cache_bytes_exact=True)
    for current in (parent,restored):
        need(current['ppl']==archive['ppl'] and current['repeated_reset_probe']==archive['repeated_reset_probe']
             and current['cache']==archive['cache'] and current['archived_ppl_replay']==parent_expected,
             'Entire archived V10 PPL/probe/cache replay differs')
    need(read(directory/'full_parent_replay.json')==comparison['parent_replay']==parent_expected,'Parent replay receipt differs')
    restoration=read(directory/'full_restoration.json');replay(parent,restored,restoration)
    for key in ('repeated_reset_probe','ppl_cache','cache','mk_cache','storage_descriptor_probe','storage_descriptor','storage_descriptor_mk'):
        need(parent[key]==restored[key],'Whole removed-adapter replay field differs: '+key)
    need(parent['mk']['summary']==restored['mk']['summary'] and parent['mk']['strata']==restored['mk']['strata']
         and all(restoration.get(k) is True for k in ('whole_reset_probe_exact','ppl_end_cache_exact','mk_end_cache_exact','all_storage_descriptors_exact'))
         and comparison['restoration']==restoration,'Whole restoration proof differs')
    change=recompute_pair(parent,candidate,np)
    gates=primary_gates(candidate['ppl']['ppl'],BASELINE_PPL,change['normal_mk_correct_delta'],
        change['normal_mk_paired_bootstrap_95ci'][0],True,True,True,True,True)
    need(comparison['comparison']==change and comparison['quality_checks']==gates
         and comparison['quality_gate_pass']==all(gates.values()) and comparison['independent_full_audit_required'] is True
         and comparison['selection_scope']=='Final1536 TRAIN export only; validation/CONFIRM never select an adapter or threshold'
         and comparison['quality_scope']==common['quality_scope']
         and comparison['memory']==dict(persistent_cache_bytes=CACHE,adapter=candidate['adapter_storage'],
             batch_size=1,static_table_bytes=57344,
             scope='Batch-one recurrent/convolution cache plus one shared static table and one adapter; source weights, temporaries and allocator reserve excluded'),
         'Independent bootstrap/strict PPL preservation/recall/memory gate differs')
    result=dict(complete=True,arms=metrics,report_sha256=digests,comparison_sha256=sha(directory/'full_comparison.json'),
        parent_replay=parent_expected,restoration=restoration,comparison=change,quality_checks=gates,quality_gate_pass=all(gates.values()))
    if args.s16_report is not None:
        need(sha(args.s16_report)==S16,'Optional S16 context changed');s16=read(args.s16_report)
        context=recompute_pair(s16,candidate,np);need(context==comparison['original_s16_comparison'],'Original S16 context differs')
        result['original_s16_comparison']=context
    else:need('original_s16_comparison' not in comparison,'Unbound S16 context present')
    return result


def self_test():
    checks=[]
    names=expected_checks();need(len(names)==len(set(names))==189,'Fixed GPU check inventory differs')
    checks.append('fixed189-check-nine-fixture-inventory')
    def gate(ppl=BASELINE_PPL,mk=1,lower=.001,cache=True):
        return primary_gates(ppl,BASELINE_PPL,mk,lower,True,True,cache,True,True)
    need(all(gate().values()) and not all(gate(math.nextafter(BASELINE_PPL,math.inf)).values()),'PPL preservation must be exact inclusive')
    checks.append('strict-no-PPL-regression-not-old1pct-tolerance')
    need(not gate(8.25)['ppl_strictly_below_8p25'] and gate(math.nextafter(8.25,0))['ppl_strictly_below_8p25'], '8.25 target boundary differs')
    checks.append('8p25-is-strict-independent-of-preservation')
    need(not all(gate(mk=0).values()) and not all(gate(lower=0).values()) and not all(gate(cache=False).values()),'Recall CI and exact budget gates missing')
    checks.append('positive-paired-CI-and-gain-and-exact-cache-required')
    initial=copy.deepcopy(INITIAL_SCALER);initial['_growth_tracker']=7
    next_scale=scaler_next(initial,True)
    need(next_scale['_growth_tracker']==7 and next_scale['scale']==512,'Overflow must preserve growth tracker')
    need(scaler_next(next_scale,False)['_growth_tracker']==8,'Retry successful tracker differs')
    checks.append('overflow-retry-full-GradScaler-state')
    initial['_growth_tracker']=1999
    need(scaler_next(initial,False)['scale']==2048 and scaler_next(initial,False)['_growth_tracker']==0,'Growth boundary differs')
    checks.append('GradScaler2000-growth-boundary')
    need(factor(0)==1. and factor(1535)==.1,'Exact inherited cosine endpoints differ')
    checks.append('fixed1536-update-cosine-endpoints')
    row=dict(prediction='123456',answer='123456',condition='normal',records=[[111111,123456],[222222,654321]])
    expected=('correct_target','wrong_present_value','not_present_value','unparseable')
    need(tuple(prediction_kind(dict(row,prediction=x)) for x in ('123456','654321','999999',None))==expected,'Normal output classification differs')
    checks.append('normal-correct-misbinding-invented-unparseable')
    removed=dict(row,condition='target_removed',records=[[222222,654321]])
    need(prediction_kind(removed)=='removed_target_match' and prediction_kind(dict(removed,prediction='654321'))=='other_present_value',
         'Removed accidental matches are not normal recall')
    checks.append('removed-target-matches-separate-diagnostic')
    rows=[dict(row,N=16,template=0,query_position=p,correct=True) for p in (0,3,4,7,8,11,12,15)]
    summary,strata=mk_summaries(rows)
    need(summary['normal']['count']==8 and all(v['count']==2 for v in strata['normal_by_N_position_quartile'].values())
         and len(strata['normal_by_N_query_position'])==8,'Position stratum arithmetic differs')
    checks.append('position-quartile-and-exact-position-partitions')
    try:audit_adapter_storage(dict(loaded=False),False,{})
    except ValueError:pass
    else:raise ValueError('Incomplete memory witness accepted')
    checks.append('incomplete-residency-witness-rejected')
    need(sum(math.prod(shape)*2 for shape in shapes().values())==ADAPTER_BYTES
         and len(shapes())==224 and CACHE+ADAPTER_BYTES==30808176,'Independent adapter payload accounting differs')
    checks.append('224-adapter-tensors-and-cache-plus-shared-adapter')
    return dict(complete=True,passed=True,count=len(checks),checks=checks,gpu_used=False)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--self-test',action='store_true')
    parser.add_argument('--stage',choices=('checks','smoke','training','full'))
    for name in ('source-dir','calibration','v10-full-dir','v10-full-audit','kernel-checks','kernel-audit',
                 'data-root','prose-tokens','prose-manifest','smoke-report','training-report','training-audit',
                 'eval-dir','s16-report','output'):
        parser.add_argument('--'+name,type=Path)
    args=parser.parse_args()
    if args.self_test:print(json.dumps(self_test(),indent=2));return
    for key in ('stage','source_dir','calibration','v10_full_dir','v10_full_audit','kernel_checks','output'):
        if getattr(args,key) is None:parser.error('--'+key.replace('_','-')+' is required')
    if args.stage!='checks':
        for key in ('kernel_audit','data_root','prose_tokens','prose_manifest','smoke_report'):
            if getattr(args,key) is None:parser.error('--'+key.replace('_','-')+' is required')
    if args.stage in ('training','full') and args.training_report is None:parser.error('--training-report is required')
    if args.stage=='full':
        for key in ('training_audit','eval_dir'):
            if getattr(args,key) is None:parser.error('--'+key.replace('_','-')+' is required')
    need(os.environ.get('CUDA_VISIBLE_DEVICES')=='','Set CUDA_VISIBLE_DEVICES= for CPU-only audit')
    need(not args.output.exists(),'Choose fresh output; retain all earlier receipts')
    os.environ['HF_HUB_OFFLINE']='1';os.environ['HF_DATASETS_OFFLINE']='1'
    dependencies=('audit_quant_first.py','audit_state_repair.py','audit_resurface_more.py','audit_state_first_v5.py',
        'audit_state_ppl_v6.py','audit_state_ppl_v8.py','audit_state_ppl_v9.py','audit_state_ppl_v10.py')
    result=dict(format=FORMAT,complete=False,passed=False,stage=args.stage,protocol_sha256=PROTOCOL,
        source_sha256=sha(__file__),checks_sha256=sha(args.kernel_checks),
        auditor_dependency_sha256={p:sha(ROOT/'scripts'/p) for p in dependencies},
        limitations=['CPU independently reconstructs recorded numerical fixture data and gradients; it does not rerun model GPU logits.',
            'Checkpoint audit verifies full finite Adam/master/scaler contents and schedules, not every GPU gradient or optimizer update.',
            'Source identity/version/gradient receipts do not constitute a post-run whole-model byte ledger.',
            'Historically exposed validation and CONFIRM families do not establish unseen generalization.',
            'Adapter cache/residency accounting excludes source weights, temporaries, allocator reserve and training scratch.'])
    try:
        import numpy as np
        import torch
        from mamba2_recall import runtime,resurface_data as data
        torch.set_num_threads(4);need(not torch.cuda.is_initialized(),'CUDA initialized before CPU audit')
        result['self_tests']=self_test()
        tokenizer=runtime.SentencePieceTokenizer(args.source_dir);need(tokenizer.sha256==TOKENIZER,'Tokenizer differs')
        _,archive,parent_binding,parent_proof=audit_parent(args,torch);result['parent']=parent_proof
        result['kernel_checks']=audit_checks(args.kernel_checks,torch,np)
        if args.stage!='checks':
            train,manifest,binding=audit_data(args,tokenizer,torch,data,parent_binding)
            canonical=read(args.kernel_audit)
            need(canonical['kernel_checks']==result['kernel_checks'] and canonical['parent']==parent_proof,
                 'Canonical kernel audit differs from raw rederivation')
            smoke=audit_training_report(args.smoke_report,'smoke',args,binding,train,manifest,tokenizer,torch,data)
            result['discarded_smoke']=smoke[1];result['smoke_report_sha256']=sha(args.smoke_report)
        if args.stage in ('training','full'):
            training,proof=audit_training_report(args.training_report,'formal',args,binding,train,manifest,tokenizer,torch,data,smoke)
            result['training']=proof;result['training_report_sha256']=sha(args.training_report)
        if args.stage=='full':
            result['full']=audit_full(args,archive,parent_binding,training,proof,tokenizer,torch,np,data)
        need(not torch.cuda.is_initialized(),'CPU audit unexpectedly initialized CUDA')
        result.update(complete=True,passed=True,cuda_initialized=False)
    except BaseException as error:
        result['error']=repr(error)
        raise
    finally:
        args.output.parent.mkdir(parents=True,exist_ok=True)
        with args.output.open('x') as stream:json.dump(result,stream,indent=2,allow_nan=False);stream.write('\n')
    print(json.dumps(result,indent=2,allow_nan=False),flush=True)


if __name__=='__main__':main()
